name: my_todo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  flutter_screenutil: ^5.5.3+2
  lottie: ^1.3.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  modal_bottom_sheet: ^2.1.0
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  sqflite: ^2.0.3
  easy_localization: ^3.0.1
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/translations/
    - assets/audio/my_music.mp3
